trigger:
    - main

#variables:
# variable group defined in Azure DevOps Library
# Optional: only when project has variable group defined in Library
  #- group: Project Variable

#ADOCS requires pipeline yaml file extending from shared template created by ADOCS team
# You should provide parameters defined in shared template (shared-template.yml) as show below
extends:
  # template: shared-template.yml@azureSharedTemplates #Refer to the resources section repo 1)
  # Below are parameters needed for shared template
  parameters:
    #parameters to set build version
    # buildVersionMajor: 1
    # buildVersionMinor: 0
    # buildPoolImage: 'windows-2022'
    #Required
    #Provide tasks which will be executed for build process
    #Below is an example of tasks for .net Core project
    buildSteps:
      - checkout: self      

     
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'D:\a\1\s\'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'AwsInfrastructure'
          publishLocation: 'pipeline'


      - task: NuGetToolInstaller@1
        inputs:
          versionSpec: '6.x'


       #Create nuspec file
      - task: CmdLine@2
        displayName: Create nuget spec file .nuspec
        inputs:
           script: 'nuget.exe spec MIMIDS.Infrastructure'
           workingDirectory: '$(Build.ArtifactStagingDirectory)'
      

      #Create Package
      - task: NuGetCommand@2
        displayName: Pack Nuget package
        inputs:
          command: 'pack'
          packagesToPack: '$(Build.ArtifactStagingDirectory)/*.nuspec'
          packDestination: '$(Build.SourcesDirectory)/nupkg'
          versioningScheme: 'byEnvVar'
          versionEnvVar: 'BUILD_BUILDNUMBER'

      - publish:
          target: '$(Pipeline.workspace)'
          artifact: 'myartifact'

      # #Push Package
      # - task: NuGetCommand@2
      #   inputs:
      #      command: 'push'
      #      packagesToPush: '$(Build.SourcesDirectory)/nupkg/*.nupkg;!$(Build.SourcesDirectory)/nupkg/**/*.symbols.nupkg'
      #      nuGetFeedType: 'external'
      #      publishFeedCredentials: 'ACR Nexus with ApiKey-ACAS10' 
           
         # - task: pipeline-triggerer-task@0
            #   inputs:
            #     adoServiceConnection: 'Azure DevOps API for triggering release from build pipeline-ACR Assist'
            #     Project: '5a76a01b-6d79-4de6-aec7-877e1898ca89'
            #     PipelineType: 'Release'
            #     ReleaseDefinition: 'Release'
            #     Async: true