# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    regionName: 'ap-northeast-1'
    stackName: 'CloudFormationStack'
    templateSource: 'file'
    templateFile: 's3-bucket-creation.yml'
    templateParametersSource: 'file'
    templateParameterFile:'ParameterFile.json'


pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
