# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main



pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      $childItems = Get-ChildItem $(System.DefaultWorkingDirectory)
      # Print the child items to the console using Write-Host
      foreach ($item in $childItems) {
          Write-Host $item.Name
      }

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    regionName: 'ap-northeast-1'
    stackName: 'cloud_formation_stack'
    templateSource: 'file'
    templateFile: '$(System.DefaultWorkingDirectory)/s3-bucket-creation.yml'
    templateParametersFile: '$(System.DefaultWorkingDirectory)/ParameterFile.json'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
